# -*- coding: utf-8 -*-
"""Addison.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ln2hA8QUyqPpnLLkOaYM1xIGj7tB8QpH
"""

a,b=10,20
print(a+b)