# -*- coding: utf-8 -*-
"""alphabet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ln2hA8QUyqPpnLLkOaYM1xIGj7tB8QpH
"""

print("abc")