# -*- coding: utf-8 -*-
"""square.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ln2hA8QUyqPpnLLkOaYM1xIGj7tB8QpH
"""

N=7
print(N*N)